spring.application.name=auth-service
server.port=8081

# Eureka - deshabilitado para desarrollo local
eureka.client.enabled=false
spring.cloud.config.enabled=false

# Oracle DataSource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=authservice
spring.datasource.password=authservice
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# JWT
jwt.secret=vrWW3CzZrbewzbGzUQuSVe/nA4LTzb+zs2bG/K3gxec=
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Springdoc
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html